// ownerEmail: String,
//   ownerUsername: String,
//   ownerPhoneNumber: String,
//   from: String,
//   to: String,
//   date: Date,
//   seats: Number,
//   detail: String,
//   passengers: Array,

const feed = [
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 3,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
];


const upcoming = [
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 3,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  },
  {
    ownerEmail: 'testemail@test.com',
    ownerUsername: 'testuser',
    ownerPhoneNumber: '9999999999',
    from: 'Los Angeles',
    to: 'San Diego',
    date: new Date(),
    price: 20,
    seats: 4,
    detail: 'some fake details about fake datas for mock testing with mock users and mock mock mock mock mock 시발',
    passengers: [],
  }
];

module.exports = {
  feed,
  upcoming,
}